// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_vrEc-i5VxRBEKG5ckyNTbXj972Te8EI',
    appId: '1:328832578420:web:4aec1f30e46b735e43b221',
    messagingSenderId: '328832578420',
    projectId: 'amancity-app',
    authDomain: 'amancity-app.firebaseapp.com',
    storageBucket: 'amancity-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-QkYVtvkr2kOheUxJJKBzPgKPdqnuZoE',
    appId: '1:328832578420:android:7713c7cdc95d2de043b221',
    messagingSenderId: '328832578420',
    projectId: 'amancity-app',
    storageBucket: 'amancity-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJhsx1PW0dvkRwdgFWzsfAY9LAVOFvyRc',
    appId: '1:328832578420:ios:f0c7eab2c857dc1243b221',
    messagingSenderId: '328832578420',
    projectId: 'amancity-app',
    storageBucket: 'amancity-app.firebasestorage.app',
    androidClientId: '328832578420-caj5fb48f6bmlqmq1tj2gmd6gclqk65i.apps.googleusercontent.com',
    iosClientId: '328832578420-fkougrkgd86gf6t0h2oknjtcm7rnv2hc.apps.googleusercontent.com',
    iosBundleId: 'com.app.amancity',
  );
}
